---
title: "Feature Plots 3D"
output: html_notebook
---

```{r}
library(plot3D)
library(tidyverse)
library(Seurat)
```

Load data
```{r}
load(file = "~/cell_lineage/Visium/V19S23-053/SLICE_2/SLICE_2_dienmidcibx_.RData")
load(file = "~/cell_lineage/Visium/V19S23-053/SLICE_1/SLICE_1_dienmidcibx_.RData")
load(file = "~/cell_lineage/Visium/V19S23-053/SLICE_3/SLICE_3_dienmidcibx_.RData")
```

Set x and y coords
```{r}
Visum.meta.1 <- SLICE_1_sub@meta.data
Visum.coords.1 <- SLICE_1_sub@images$SLICE_1@coordinates 
Visum.meta.1 <- cbind(Visum.meta.1, Visum.coords.1)
Visum.meta.1$Spot <- rownames(Visum.meta.1)
rownames(Visum.meta.1) <- gsub("-1","_S1", rownames(Visum.meta.1))
Visum.meta.1$Z = 3
Visum.meta.1$col.sc = scale(Visum.meta.1$col)
Visum.meta.1$row.sc = scale(Visum.meta.1$row)

Visum.meta.2 <- SLICE_2_sub@meta.data
Visum.coords.2 <- SLICE_2_sub@images$SLICE_2@coordinates 
Visum.meta.2 <- cbind(Visum.meta.2, Visum.coords.2)
Visum.meta.2$Spot <- rownames(Visum.meta.2)
rownames(Visum.meta.2) <- gsub("-1","_S2", rownames(Visum.meta.2))
Visum.meta.2$Z = 2
Visum.meta.2$col.sc = scale(Visum.meta.2$col)
Visum.meta.2$row.sc = scale(Visum.meta.2$row)

Visum.meta.3 <- SLICE_3@meta.data
Visum.coords.3 <- SLICE_3@images$SLICE_3@coordinates 
Visum.meta.3 <- cbind(Visum.meta.3, Visum.coords.3)
Visum.meta.3$Spot <- rownames(Visum.meta.3)
rownames(Visum.meta.3) <- gsub("-1","_S3", rownames(Visum.meta.3))
Visum.meta.3$Z = 1
Visum.meta.3$col.sc = scale(Visum.meta.3$col)
Visum.meta.3$row.sc = scale(Visum.meta.3$row)

Visum.meta.all = rbind(Visum.meta.1, Visum.meta.2, Visum.meta.3, stringsAsFactors=F)
```

set z
```{r}
Visum.meta.all$ZZ <- Visum.meta.all$Z
Visum.meta.all$ZZ <- gsub(pattern = 3, replacement = 6, x = Visum.meta.all$ZZ) #section 1
Visum.meta.all$ZZ <- gsub(pattern = 2, replacement = 3, x = Visum.meta.all$ZZ) #section 2
Visum.meta.all$ZZ <- gsub(pattern = 1, replacement = -2, x = Visum.meta.all$ZZ) #section 3
table(Visum.meta.all$ZZ)
```

Pull Feature Genes
```{r}
Visium.markers.1 <- FetchData(object = SLICE_1_sub, vars = c("FOXG1", "HOXB2", "OTX2", "DCN", "SOX10", "EPCAM", "HOXB5", "ROBO3", "Tomato"))
rownames(Visium.markers.1) <- gsub("-1","_S1", rownames(Visium.markers.1))

Visium.markers.2 <- FetchData(object = SLICE_2_sub, vars = c("FOXG1", "HOXB2", "OTX2", "DCN", "SOX10", "EPCAM", "HOXB5", "ROBO3", "Tomato"))
rownames(Visium.markers.2) <- gsub("-1","_S1", rownames(Visium.markers.2))

Visium.markers.3 <- FetchData(object = SLICE_3, vars = c("FOXG1", "HOXB2", "OTX2", "DCN", "SOX10", "EPCAM", "HOXB5", "ROBO3", "Tomato"))
rownames(Visium.markers.3) <- gsub("-1","_S1", rownames(Visium.markers.3))

Visium.markers.all <- rbind(Visium.markers.1, Visium.markers.2, Visium.markers.3, stringsAsFactors=F)

Visium_mark_meta <- cbind(Visum.meta.all, Visium.markers.all)
```

Make feature plots for visium data
```{r}
pdf("~/cell_lineage/Visium/V19S23-053/Tomato_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$Tomato))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/FOXG1_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$FOXG1))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/ROBO3_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$ROBO3))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/HOXB2_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$HOXB2))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```


```{r}
pdf("~/cell_lineage/Visium/V19S23-053/HOXB5_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$HOXB5))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/OTX2_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$OTX2))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/DCN_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$DCN))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/SOX10_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$SOX10))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
pdf("~/cell_lineage/Visium/V19S23-053/EPCAM_3D.pdf")
scatter3D(x = Visium_mark_meta$row.sc, y = Visium_mark_meta$col.sc,
          z = as.numeric(Visium_mark_meta$ZZ),
          colvar = as.numeric(as.factor(scale(Visium_mark_meta$EPCAM))),
          col = ramp.col(c("#cdcdcd","#edf8b1","#7fcdbb","#41b6c4","#1d91c0","#225ea8","#0c2c84")),
          bty = "n", pch = 19, cex = 1.0, theta = 75, phi = 30, colkey = TRUE)
dev.off()
```

```{r}
read.csv(file = "~/cell_lineage/Visium/V19S23-053/visium_barcodesbi.csv")
visium_barcodes_bi <- Visium_mark_meta$X <- rownames(Visium_mark_meta)
barcodes_and_features <- left_join(Visium_mark_meta, visium_barcodes_bi, by = "X")
rownames(barcodes_and_features) <- barcodes_and_features$X

```

```{r}
table(barcodes_and_features$Z.x)
withcolor <- ggplot(barcodes_and_features, aes(x = barcodesum, y = Tomato, colour = factor(Z.x))) + geom_point() + theme_classic()
withoutcolor <- ggplot(barcodes_and_features, aes(x = barcodesum, y = Tomato)) + geom_point() + theme_classic()

ggsave(plot = withcolor, filename = "~/cell_lineage/Visium/V19S23-053/barcodes_vs_tomato_wslicescolored.pdf")
ggsave(plot = withoutcolor, filename = "~/cell_lineage/Visium/V19S23-053/barcodes_vs_tomato.pdf")
```

```{r}
mean(visium_barcodes_bi$nCount_SCT)
mean(visium_barcodes_bi$nFeature_Spatial)
table(visium_barcodes_bi$hasbarcode)
```

find % mito
```{r}
SLICE_1_sub
SLICE_2_sub
SLICE_3
x <- PercentageFeatureSet(SLICE_1_sub, pattern = "^MT-")
y <- PercentageFeatureSet(SLICE_2_sub, pattern = "^MT-")
z <- PercentageFeatureSet(SLICE_3, pattern = "^MT-")
w <- rbind(x, y)
v <- rbind (w, z)
mean(v$nCount_SCT)
```

